#!/usr/bin/env python3
"""
AutoDocGen - Automatic API Documentation Generator
Scans Python code (FastAPI/Flask/Django) and generates structured documentation.
"""

import os
import ast
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from datetime import datetime


@dataclass
class EndpointInfo:
    """Represents a single API endpoint."""
    method: str
    path: str
    summary: str
    description: str
    parameters: List[Dict[str, Any]]
    request_body: Optional[Dict[str, Any]]
    responses: Dict[str, Any]
    auth_required: bool
    tags: List[str]
    source_file: str
    line_number: int


@dataclass
class APISpec:
    """Complete API specification."""
    title: str
    version: str
    description: str
    base_url: str
    endpoints: List[EndpointInfo]
    schemas: Dict[str, Any]
    auth_methods: List[str]


class CodeParser:
    HTTP_METHODS = {'get', 'post', 'put', 'patch', 'delete', 'head', 'options'}
    
    def __init__(self, source_dir: str):
        self.source_dir = Path(source_dir)
        self.endpoints = []
        self.schemas = {}
        
    def parse_all(self) -> APISpec:
        """Parse all Python files in the source directory."""
        for py_file in self.source_dir.rglob('*.py'):
            self._parse_file(py_file)
        return APISpec(
            title="Auto-Generated API Documentation",
            version="1.0.0",
            description="Documentation generated by AutoDocGen",
            base_url="/api/v1",
            endpoints=sorted(self.endpoints, key=lambda e: e.path),
            schemas=self.schemas,
            auth_methods=["Bearer Token", "API Key"]
        )
    
    def _parse_file(self, file_path: Path):
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                source = f.read()
            tree = ast.parse(source)
            for node in ast.walk(tree):
                # FIX: Check both FunctionDef and AsyncFunctionDef
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    endpoint = self._extract_endpoint(node, file_path, source)
                    if endpoint:
                        self.endpoints.append(endpoint)
                elif isinstance(node, ast.ClassDef):
                    schema = self._extract_schema(node, source)
                    if schema:
                        self.schemas[schema['name']] = schema
        except SyntaxError:
            pass
    
    def _extract_endpoint(self, node, file_path, source):
        route_info = self._find_route_decorator(node)
        if not route_info:
            return None
        docstring = ast.get_docstring(node) or ""
        summary = docstring.split('\n')[0] if docstring else "No description"
        return EndpointInfo(
            method=route_info['method'].upper(),
            path=route_info['path'],
            summary=summary,
            description=docstring,
            parameters=self._extract_parameters(node),
            request_body=self._extract_request_body(node),
            responses=self._extract_responses(node, docstring),
            auth_required=self._check_auth(node, source),
            tags=[file_path.stem],
            source_file=str(file_path),
            line_number=node.lineno
        )
    
    def _find_route_decorator(self, node):
        for decorator in node.decorator_list:
            if isinstance(decorator, ast.Call):
                func = decorator.func
                if isinstance(func, ast.Attribute):
                    method = func.attr.lower()
                    if method in self.HTTP_METHODS:
                        path = self._extract_path(decorator)
                        if path:
                            return {'method': method, 'path': path}
                elif isinstance(func, ast.Name) and func.id == 'route':
                    path = self._extract_path(decorator)
                    method = self._extract_methods(decorator) or 'get'
                    if path:
                        return {'method': method, 'path': path}
        return None
    
    def _extract_path(self, decorator):
        if decorator.args:
            first_arg = decorator.args[0]
            if isinstance(first_arg, ast.Constant) and isinstance(first_arg.value, str):
                return first_arg.value
        return None
    
    def _extract_methods(self, decorator):
        for keyword in decorator.keywords:
            if keyword.arg == 'methods':
                if isinstance(keyword.value, ast.List):
                    methods = []
                    for elt in keyword.value.elts:
                        if isinstance(elt, ast.Constant):
                            methods.append(elt.value.lower())
                    return methods[0] if methods else None
        return None
    
    def _extract_parameters(self, node):
        parameters = []
        for arg in node.args.args:
            param_name = arg.arg
            if param_name in {'self', 'cls', 'request', 'db'}:
                continue
            param_type = self._get_type_annotation(arg)
            param_info = {
                'name': param_name, 'in': 'query', 'type': param_type,
                'required': True, 'description': f"Parameter: {param_name}"
            }
            if param_type in {'dict', 'Dict', 'BaseModel'}:
                param_info['in'] = 'body'
            parameters.append(param_info)
        return parameters
    
    def _get_type_annotation(self, arg):
        if arg.annotation:
            if isinstance(arg.annotation, ast.Name):
                return arg.annotation.id
            elif isinstance(arg.annotation, ast.Constant):
                return str(arg.annotation.value)
            elif hasattr(ast, 'unparse'):
                return ast.unparse(arg.annotation)
        return "string"
    
    def _check_auth(self, node, source):
        func_source = ast.unparse(node) if hasattr(ast, 'unparse') else ""
        auth_indicators = ['Depends(verify', 'Depends(get_current', 'api_key', 'auth', 'authorization', 'login_required', 'jwt']
        return any(indicator in func_source.lower() for indicator in auth_indicators)
    
    def _extract_responses(self, node, docstring):
        responses = {
            '200': {'description': 'Success', 'schema': None},
            '401': {'description': 'Unauthorized', 'schema': None},
            '422': {'description': 'Validation Error', 'schema': None},
            '500': {'description': 'Internal Server Error', 'schema': None}
        }
        if node.returns and hasattr(ast, 'unparse'):
            responses['200']['schema'] = ast.unparse(node.returns)
        return responses
    
    def _extract_request_body(self, node):
        for arg in node.args.args:
            param_type = self._get_type_annotation(arg)
            if param_type.endswith('Model') or param_type.endswith('Schema'):
                return {'name': arg.arg, 'schema': param_type, 'required': True}
        return None
    
    def _extract_schema(self, node, source):
        base_names = [base.id for base in node.bases if isinstance(base, ast.Name)]
        if not any(base in {'BaseModel', 'Model'} for base in base_names):
            return None
        fields = []
        for item in node.body:
            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                field_type = ast.unparse(item.annotation) if hasattr(ast, 'unparse') else "Any"
                fields.append({'name': item.target.id, 'type': field_type})
        return {'name': node.name, 'fields': fields, 'base_classes': base_names}


# [HTMLGenerator class and main() function remain the same as before]

def main():
    import argparse
    import sys
    
    parser = argparse.ArgumentParser(description='AutoDocGen - Generate API documentation from Python code')
    parser.add_argument('source', help='Source directory containing Python files')
    parser.add_argument('-o', '--output', default='api-docs.html', help='Output HTML file')
    parser.add_argument('--title', default='API Documentation', help='API title')
    
    args = parser.parse_args()
    
    if not os.path.isdir(args.source):
        print(f"Error: Directory not found: {args.source}")
        sys.exit(1)
    
    print(f"Scanning {args.source}...")
    parser = CodeParser(args.source)
    spec = parser.parse_all()
    spec.title = args.title
    
    print(f"Found {len(spec.endpoints)} endpoints and {len(spec.schemas)} schemas")
    print(f"Generating HTML...")
    generator = HTMLGenerator(spec)
    html = generator.generate()
    
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(html)
    
    print(f"Documentation generated: {os.path.abspath(args.output)}")
    print(f"Open in browser: file://{os.path.abspath(args.output)}")


if __name__ == '__main__':
    main()